/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendapinturas.views;

import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import tiendapinturas.DatabaseConnection;
import tiendapinturas.models.Usuario;
import tiendapinturas.controllers.ExportadorUtil;
import tiendapinturas.models.Producto;

/**
 *
 * @author vicga
 */
public class HistorialFrameGUI extends javax.swing.JFrame {
    
    private Usuario usuario;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistorialFrameGUI.class.getName());

    /**
     * Creates new form HistorialFrameGUI
     */
    
    public HistorialFrameGUI(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Historial de Ventas - " + usuario.getNombre());
        cargarHistorial();
    }
    
    // Constructor vacío
    public HistorialFrameGUI() {
        initComponents();
        setLocationRelativeTo(null);
        cargarHistorial();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial de Ventas");
        setPreferredSize(new java.awt.Dimension(665, 430));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Historal de Ventas");

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Venta", "Ticket", "Fecha", "Cliente", "Vendedor", "Total", "Pago", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        btnCerrar.setText("❌ Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnVolver.setText("🏠 Volver al Menú");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnVerDetalle.setText("🔍 Ver Detalle");
        btnVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleActionPerformed(evt);
            }
        });

        btnActualizar.setText("🔄 Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnExportar.setText("📤 Exportar Producto");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnActualizar)
                    .addComponent(btnVerDetalle)
                    .addComponent(btnCerrar)
                    .addComponent(btnExportar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarHistorial();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHistorial.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Seleccione una venta para ver el detalle",
                "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int ventaId = (int) tblHistorial.getValueAt(selectedRow, 0);
        mostrarDetalleVenta(ventaId);
    }//GEN-LAST:event_btnVerDetalleActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
         if (usuario != null) {
            new MainFrameGUI(usuario).setVisible(true);
        } else {
            new MainFrameGUI().setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblHistorial.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione una venta primero",
            "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Obtener ID de la venta
    int ventaId = (int) tblHistorial.getValueAt(selectedRow, 0);
    
    // Obtener el primer producto de la venta para demostración
    String sql = "SELECT p.* FROM detalle_ventas dv " +
                "JOIN productos p ON dv.producto_id = p.producto_id " +
                "WHERE dv.venta_id = ? LIMIT 1";
    
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setInt(1, ventaId);
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            // Crear objeto Producto (que implementa Exportable)
            Producto producto = new Producto(
                rs.getInt("producto_id"),
                rs.getString("codigo"),
                rs.getString("nombre"),
                rs.getString("categoria"),
                rs.getDouble("precio"),
                rs.getInt("stock")
            );
            
            // ¡POLIMORFISMO EN ACCIÓN!
            // ExportadorUtil.exportar() acepta CUALQUIER objeto que implemente Exportable
            boolean exito = ExportadorUtil.exportarConMensaje(
                producto,  // producto ES un Exportable
                "Exportar Producto"
            );
            
            if (exito) {
                System.out.println("Producto exportado: " + producto.obtenerNombreArchivo());
            }
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se encontraron productos en esta venta",
                "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void cargarHistorial() {
        DefaultTableModel model = (DefaultTableModel) tblHistorial.getModel();
        model.setRowCount(0);  // Limpiar tabla
        
        String sql = "SELECT " +
                     "v.venta_id, " +
                     "v.numero_ticket, " +
                     "v.fecha, " +
                     "c.nombre AS cliente, " +
                     "ve.nombre AS vendedor, " +
                     "v.total, " +
                     "v.metodo_pago, " +
                     "CASE WHEN v.total > 0 THEN 'COMPLETADA' ELSE 'PENDIENTE' END AS estado " +
                     "FROM ventas v " +
                     "LEFT JOIN clientes c ON v.cliente_id = c.cliente_id " +
                     "LEFT JOIN vendedores ve ON v.vendedor_id = ve.vendedor_id " +
                     "ORDER BY v.fecha DESC, v.venta_id DESC";
        
        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            
            while (rs.next()) {
                java.util.Date fecha = rs.getDate("fecha");
                String fechaStr = (fecha != null) ? dateFormat.format(fecha) : "N/A";
                
                Object[] row = {
                    rs.getInt("venta_id"),
                    rs.getString("numero_ticket"),
                    fechaStr,
                    rs.getString("cliente") != null ? rs.getString("cliente") : "N/A",
                    rs.getString("vendedor") != null ? rs.getString("vendedor") : "N/A",
                    String.format("$%.2f", rs.getDouble("total")),
                    rs.getString("metodo_pago"),
                    rs.getString("estado")
                };
                model.addRow(row);
            }
            
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al cargar historial: " + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void mostrarDetalleVenta(int ventaId) {
    // Obtener información completa de la venta
    String sqlVenta = "SELECT v.*, c.nombre as nombre_cliente, ve.nombre as nombre_vendedor " +
                     "FROM ventas v " +
                     "LEFT JOIN clientes c ON v.cliente_id = c.cliente_id " +
                     "LEFT JOIN vendedores ve ON v.vendedor_id = ve.vendedor_id " +
                     "WHERE v.venta_id = ?";
    
    // Obtener detalles de productos
    String sqlDetalle = "SELECT p.codigo, p.nombre, dv.cantidad, dv.precio_unitario, dv.subtotal_linea " +
                       "FROM detalle_ventas dv " +
                       "JOIN productos p ON dv.producto_id = p.producto_id " +
                       "WHERE dv.venta_id = ?";
    
    StringBuilder ticket = new StringBuilder();
    double totalVenta = 0;
    String numeroTicket = "";
    String fechaVenta = "";
    String cliente = "";
    String vendedor = "";
    String metodoPago = "";
    
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement pstmtVenta = conn.prepareStatement(sqlVenta);
         PreparedStatement pstmtDetalle = conn.prepareStatement(sqlDetalle)) {
        
        // Obtener información de la venta
        pstmtVenta.setInt(1, ventaId);
        ResultSet rsVenta = pstmtVenta.executeQuery();
        
        if (rsVenta.next()) {
            numeroTicket = rsVenta.getString("numero_ticket");
            fechaVenta = rsVenta.getDate("fecha").toString();
            cliente = rsVenta.getString("nombre_cliente") != null ? 
                     rsVenta.getString("nombre_cliente") : "N/A";
            vendedor = rsVenta.getString("nombre_vendedor") != null ? 
                      rsVenta.getString("nombre_vendedor") : "N/A";
            metodoPago = rsVenta.getString("metodo_pago");
            totalVenta = rsVenta.getDouble("total");
            
            // Construir encabezado del ticket
            ticket.append("══════════════════════════════════════════════\n");
            ticket.append("              TIENDA DE PINTURAS             \n");
            ticket.append("══════════════════════════════════════════════\n");
            ticket.append("Ticket: ").append(numeroTicket).append("\n");
            ticket.append("Venta ID: ").append(ventaId).append("\n");
            ticket.append("Fecha: ").append(fechaVenta).append("\n");
            ticket.append("Vendedor: ").append(vendedor).append("\n");
            ticket.append("Cliente: ").append(cliente).append("\n");
            ticket.append("Método Pago: ").append(metodoPago).append("\n");
            ticket.append("══════════════════════════════════════════════\n");
            ticket.append("PRODUCTOS:\n");
            ticket.append("══════════════════════════════════════════════\n");
        }
        
        // Obtener detalles de productos
        pstmtDetalle.setInt(1, ventaId);
        ResultSet rsDetalle = pstmtDetalle.executeQuery();
        
        double subtotal = 0;
        int item = 1;
        
        while (rsDetalle.next()) {
            String codigo = rsDetalle.getString("codigo");
            String nombre = rsDetalle.getString("nombre");
            int cantidad = rsDetalle.getInt("cantidad");
            double precio = rsDetalle.getDouble("precio_unitario");
            double subtotalLinea = rsDetalle.getDouble("subtotal_linea");
            
            ticket.append(String.format("%d. %s - %s\n", item++, codigo, nombre));
            ticket.append(String.format("   Cantidad: %d x $%.2f = $%.2f\n\n", cantidad, precio, subtotalLinea));
            
            subtotal += subtotalLinea;
        }
        
        if (item == 1) {
            ticket.append("No se encontraron productos para esta venta.\n");
        } else {
            double iva = subtotal * 0.16;
            double total = subtotal + iva;
            
            ticket.append("══════════════════════════════════════════════\n");
            ticket.append(String.format("SUBTOTAL:              $%.2f\n", subtotal));
            ticket.append(String.format("IVA (16%%):             $%.2f\n", iva));
            ticket.append(String.format("TOTAL:                 $%.2f\n", total));
            ticket.append("══════════════════════════════════════════════\n");
            ticket.append("         ¡GRACIAS POR SU COMPRA!             \n");
            ticket.append("══════════════════════════════════════════════\n");
        }
        
        // Crear área de texto para mostrar
javax.swing.JTextArea textArea = new javax.swing.JTextArea(ticket.toString());
textArea.setEditable(false);
textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
scrollPane.setPreferredSize(new java.awt.Dimension(500, 400));

// Crear variables finales para usar en lambda
final String ticketContenido = ticket.toString();
final String nombreArchivo = "Ticket_" + 
    (numeroTicket != null && !numeroTicket.isEmpty() ? numeroTicket : "Venta_" + ventaId);

// Crear botón para guardar
javax.swing.JButton btnGuardar = new javax.swing.JButton("💾 Guardar Ticket como TXT");
btnGuardar.addActionListener(e -> guardarTicketArchivo(ticketContenido, nombreArchivo));

// Crear panel con botón
javax.swing.JPanel panelBotones = new javax.swing.JPanel();
panelBotones.add(btnGuardar);

// Crear panel principal
javax.swing.JPanel panelPrincipal = new javax.swing.JPanel(new java.awt.BorderLayout());
panelPrincipal.add(scrollPane, java.awt.BorderLayout.CENTER);
panelPrincipal.add(panelBotones, java.awt.BorderLayout.SOUTH);

// Mostrar diálogo
javax.swing.JOptionPane.showMessageDialog(this, panelPrincipal, 
    "Ticket de Venta - " + (numeroTicket != null ? numeroTicket : ventaId), 
    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al cargar detalle: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void guardarTicketArchivo(String contenido, String nombreArchivo) {
    // Crear selector de archivos
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    
    // Sugerir nombre de archivo
    fileChooser.setSelectedFile(new java.io.File(nombreArchivo + ".txt"));
    
    // Mostrar diálogo de guardar
    int resultado = fileChooser.showSaveDialog(this);
    
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        
        // Asegurar extensión .txt
        if (!archivo.getName().toLowerCase().endsWith(".txt")) {
            archivo = new java.io.File(archivo.getAbsolutePath() + ".txt");
        }
        
        try (java.io.FileWriter writer = new java.io.FileWriter(archivo)) {
            writer.write(contenido);
            
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ticket guardado exitosamente en:\n" + archivo.getAbsolutePath(),
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al guardar el archivo:\n" + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HistorialFrameGUI().setVisible(true));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HistorialFrameGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables
}
