/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendapinturas.views;

import tiendapinturas.models.Usuario;
import tiendapinturas.models.Producto;
import tiendapinturas.DatabaseConnection;
import tiendapinturas.controllers.ProductoController;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.io.FileWriter;
import java.io.IOException;

public class VentasFrameGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentasFrameGUI.class.getName());
    
    private Usuario vendedor;
    private List<Producto> carrito = new ArrayList<>();
    private DefaultTableModel modelProductos;
    private DefaultTableModel modelCarrito;
    private List<ClienteCombo> listaClientes = new ArrayList<>();
    
    // Clase interna para combo de clientes
    private class ClienteCombo {
        private int id;
        private String nombre;
        
        public ClienteCombo(int id, String nombre) {
            this.id = id;
            this.nombre = nombre;
        }
        
        public int getId() { return id; }
        public String getNombre() { return nombre; }
        
        @Override
        public String toString() {
            return nombre;
        }
    }
    
    public VentasFrameGUI(Usuario vendedor) {
        this.vendedor = vendedor;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Registrar Venta - " + vendedor.getNombre());
        
        configurarTablas();       
        cargarProductosDisponibles();        
        cargarClientes();       
        configurarBotones();
    }
    
    public VentasFrameGUI() {
        initComponents();
        setLocationRelativeTo(null);
        configurarTablas();
        cargarProductosDisponibles();
        cargarClientes();
        configurarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblVendedor = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnFinalizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        btnNuevoCliente = new javax.swing.JButton();
        cmbClientes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Venta");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Registrar Venta");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Vendedor");

        lblVendedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblVendedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFinalizar.setText("💰 FINALIZAR VENTA");

        btnCancelar.setText("❌ CANCELAR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinalizar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Codigo", "Nombre", "Categoria", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jLabel3.setText("Cantidad");

        txtCantidad.setColumns(5);
        txtCantidad.setText("1");

        btnAgregar.setText("➕ Agregar al Carrito");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos Disponibles", jPanel2);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tblCarrito);

        btnLimpiar.setText("🗑️ Limpiar Carrito");

        btnQuitar.setText("➖ Quitar Seleccionado");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSubtotal.setText("Subtotal: $0.00");

        lblIVA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIVA.setText("IVA (16%): $0.00");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total: $0.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIVA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnQuitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carrito de Compras", jPanel4);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cliente");

        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "TARJETA DÉBITO  ", "TARJETA CRÉDITO", "TRANSFERENCIA", "CHEQUE" }));

        btnNuevoCliente.setText("➕ Nuevo Cliente");

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Metodo de Pago");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMetodoPago, 0, 1, Short.MAX_VALUE)
                    .addComponent(cmbClientes, 0, 129, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(btnNuevoCliente)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnNuevoCliente)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarActionPerformed

    /**
     * @param args the command line arguments
     */
    
     private void configurarTablas() {
        // Configurar tabla de productos
        modelProductos = (DefaultTableModel) tblProductos.getModel();
        // Configurar tabla del carrito
        modelCarrito = (DefaultTableModel) tblCarrito.getModel();
    }
     
     private void configurarBotones() {
        // Mostrar nombre del vendedor
        if (vendedor != null) {
            lblVendedor.setText(vendedor.getNombre());
        } else {
            lblVendedor.setText("No asignado");
        }
        
        btnAgregar.addActionListener(evt -> agregarAlCarrito());
        btnQuitar.addActionListener(evt -> quitarDelCarrito());
        btnLimpiar.addActionListener(evt -> limpiarCarrito());
        btnFinalizar.addActionListener(evt -> finalizarVenta());
        btnCancelar.addActionListener(evt -> dispose());
        btnNuevoCliente.addActionListener(evt -> crearNuevoCliente());
    }
     
      private void cargarClientes() {
    listaClientes.clear();
    cmbClientes.removeAllItems();
    
    String sql = "SELECT cliente_id, nombre FROM clientes ORDER BY nombre";
    
    try (Connection conn = DatabaseConnection.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {
        
        while (rs.next()) {
            int id = rs.getInt("cliente_id");
            String nombre = rs.getString("nombre");
            
            // Guardar en lista de objetos
            listaClientes.add(new ClienteCombo(id, nombre));
            
            // Agregar solo el nombre (String) al ComboBox
            cmbClientes.addItem(nombre);
        }
        
        if (listaClientes.isEmpty()) {
            cmbClientes.addItem("SIN CLIENTES");
        }
        
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al cargar clientes: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
      
    private void crearNuevoCliente() {
    String nombre = javax.swing.JOptionPane.showInputDialog(this,
        "Nombre del nuevo cliente:", "Nuevo Cliente");
    
    if (nombre == null || nombre.trim().isEmpty()) {
        return;
    }
    
    String telefono = javax.swing.JOptionPane.showInputDialog(this,
        "Teléfono del cliente (opcional):", "Nuevo Cliente");
    
    String email = javax.swing.JOptionPane.showInputDialog(this,
        "Email del cliente (opcional):", "Nuevo Cliente");
    
    String sql = "INSERT INTO clientes (nombre, telefono, email, fecha_registro) VALUES (?, ?, ?, CURDATE())";
    
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
        
        pstmt.setString(1, nombre.trim());
        pstmt.setString(2, telefono != null ? telefono.trim() : "");
        pstmt.setString(3, email != null ? email.trim() : "");
        
        pstmt.executeUpdate();
        
        ResultSet rs = pstmt.getGeneratedKeys();
        if (rs.next()) {
            int nuevoId = rs.getInt(1);
            
            // CORREGIDO: Solo agregar el nombre al ComboBox
            ClienteCombo nuevoCliente = new ClienteCombo(nuevoId, nombre.trim());
            listaClientes.add(nuevoCliente);
            
            // Agregar solo el nombre (String) al ComboBox
            cmbClientes.addItem(nombre.trim());
            
            // Seleccionar el nuevo cliente
            cmbClientes.setSelectedItem(nombre.trim());
            
            javax.swing.JOptionPane.showMessageDialog(this,
                "Cliente creado exitosamente",
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al crear cliente: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
     
     private void cargarProductosDisponibles() {
        modelProductos.setRowCount(0);
        List<Producto> productos = ProductoController.obtenerProductosDisponibles();
        
        for (Producto p : productos) {
            Object[] row = {
                p.getId(),
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                String.format("$%.2f", p.getPrecio()),
                p.getStock()
            };
            modelProductos.addRow(row);
        }
    }
     
     private void agregarAlCarrito() {
        int selectedRow = tblProductos.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Seleccione un producto de la tabla", 
                "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int productoId = (int) modelProductos.getValueAt(selectedRow, 0);
            String codigo = (String) modelProductos.getValueAt(selectedRow, 1);
            String nombre = (String) modelProductos.getValueAt(selectedRow, 2);
            double precio = Double.parseDouble(((String) modelProductos.getValueAt(selectedRow, 4)).replace("$", ""));
            int stock = (int) modelProductos.getValueAt(selectedRow, 5);
            
            int cantidad;
            try {
                cantidad = Integer.parseInt(txtCantidad.getText().trim());
                if (cantidad <= 0) throw new NumberFormatException();
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Ingrese una cantidad válida", 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (cantidad > stock) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Stock insuficiente. Disponible: " + stock, 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            for (int i = 0; i < carrito.size(); i++) {
                Producto p = carrito.get(i);
                if (p.getId() == productoId) {
                    int opcion = javax.swing.JOptionPane.showConfirmDialog(this,
                        "El producto ya está en el carrito. ¿Actualizar cantidad?",
                        "Producto duplicado", javax.swing.JOptionPane.YES_NO_OPTION);
                    
                    if (opcion == javax.swing.JOptionPane.YES_OPTION) {
                        carrito.set(i, new Producto(productoId, codigo, nombre, "", precio, cantidad));
                        actualizarCarrito();
                    }
                    return;
                }
            }
            
            Producto producto = new Producto(productoId, codigo, nombre, "", precio, cantidad);
            carrito.add(producto);
            actualizarCarrito();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
     
    private void quitarDelCarrito() {
        int selectedRow = tblCarrito.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Seleccione un producto del carrito", 
                "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String codigo = (String) modelCarrito.getValueAt(selectedRow, 0);
        
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Eliminar " + codigo + " del carrito?",
            "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            carrito.remove(selectedRow);
            actualizarCarrito();
        }
    }
    
    private void limpiarCarrito() {
        if (carrito.isEmpty()) return;
        
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this,
            "¿Eliminar todos los productos del carrito?",
            "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            carrito.clear();
            actualizarCarrito();
        }
    }
    
    private void actualizarCarrito() {
         modelCarrito.setRowCount(0);
        double subtotal = 0;
        
        for (Producto p : carrito) {
            double precio = p.getPrecio();
            int cantidad = p.getStock();
            double subtotalLinea = precio * cantidad;
            subtotal += subtotalLinea;
            
            Object[] row = {
                p.getCodigo(),
                p.getNombre(),
                cantidad,
                String.format("$%.2f", precio),
                String.format("$%.2f", subtotalLinea)
            };
            modelCarrito.addRow(row);
        }
        
        double iva = subtotal * 0.16;
        double total = subtotal + iva;
        
        lblSubtotal.setText(String.format("Subtotal: $%.2f", subtotal));
        lblIVA.setText(String.format("IVA (16%%): $%.2f", iva));
        lblTotal.setText(String.format("TOTAL: $%.2f", total));
    }
    
    private void finalizarVenta() {
        if (carrito.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El carrito está vacío", 
            "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Obtener cliente seleccionado (como String)
        String nombreCliente = (String) cmbClientes.getSelectedItem();
        if (nombreCliente == null || nombreCliente.equals("SIN CLIENTES") || nombreCliente.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Seleccione un cliente válido", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    
    // Buscar el ID del cliente por nombre
    int clienteId = 0;
    for (ClienteCombo cliente : listaClientes) {
        if (cliente.getNombre().equals(nombreCliente)) {
            clienteId = cliente.getId();
            break;
        }
    }
    
    // Si no encontramos el cliente en la lista (puede ser nuevo)
    if (clienteId == 0) {
        // Puede ser un cliente recién creado que no está en listaClientes
        // Buscar en la base de datos
        String sql = "SELECT cliente_id FROM clientes WHERE nombre = ? LIMIT 1";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, nombreCliente);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                clienteId = rs.getInt("cliente_id");
                // Agregar a listaClientes para futuras referencias
                listaClientes.add(new ClienteCombo(clienteId, nombreCliente));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Cliente no encontrado en la base de datos", 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al buscar cliente: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
        // Obtener método de pago
        String metodoPago = (String) cmbMetodoPago.getSelectedItem();
        if (metodoPago == null || metodoPago.isEmpty()) {
            metodoPago = "EFECTIVO";
        }
    
    
        // Confirmar venta
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
            "Cliente: " + nombreCliente + "\n" +
            "Método de Pago: " + metodoPago + "\n" +
            "Total: " + lblTotal.getText() + "\n\n" +
            "¿Confirmar venta?",
            "Confirmar Venta", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        
        Connection conn = null;
        try {
            conn = DatabaseConnection.getConnection();
            conn.setAutoCommit(false);
            
            String sqlVenta = "INSERT INTO ventas (numero_ticket, fecha, cliente_id, vendedor_id, " +
                             "subtotal, iva, total, metodo_pago) " +
                             "VALUES (?, CURDATE(), ?, ?, ?, ?, ?, ?)";
            
            String numeroTicket = "TKT-" + System.currentTimeMillis();
            
            double subtotal = 0;
            for (Producto p : carrito) {
                subtotal += p.getPrecio() * p.getStock();
            }
            double iva = subtotal * 0.16;
            double total = subtotal + iva;
            
            try (PreparedStatement pstmt = conn.prepareStatement(sqlVenta, Statement.RETURN_GENERATED_KEYS)) {
                pstmt.setString(1, numeroTicket);
                pstmt.setInt(2, clienteId);
                pstmt.setInt(3, vendedor != null ? vendedor.getId() : 1);
                pstmt.setDouble(4, subtotal);
                pstmt.setDouble(5, iva);
                pstmt.setDouble(6, total);
                pstmt.setString(7, metodoPago);
                
                pstmt.executeUpdate();
                
                ResultSet rs = pstmt.getGeneratedKeys();
                int ventaId = 0;
                if (rs.next()) {
                    ventaId = rs.getInt(1);
                }
                
                for (Producto p : carrito) {
                    String sqlDetalle = "INSERT INTO detalle_ventas (venta_id, producto_id, cantidad, precio_unitario) " +
                                       "VALUES (?, ?, ?, ?)";
                    try (PreparedStatement pstmtDetalle = conn.prepareStatement(sqlDetalle)) {
                        pstmtDetalle.setInt(1, ventaId);
                        pstmtDetalle.setInt(2, p.getId());
                        pstmtDetalle.setInt(3, p.getStock());
                        pstmtDetalle.setDouble(4, p.getPrecio());
                        pstmtDetalle.executeUpdate();
                    }
                    
                    String sqlUpdateStock = "UPDATE productos SET stock = stock - ? WHERE producto_id = ?";
                    try (PreparedStatement pstmtStock = conn.prepareStatement(sqlUpdateStock)) {
                        pstmtStock.setInt(1, p.getStock());
                        pstmtStock.setInt(2, p.getId());
                        pstmtStock.executeUpdate();
                    }
                    
                    String sqlMovimiento = "INSERT INTO movimientos_inventario (producto_id, tipo_movimiento, cantidad, referencia) " +
                                          "VALUES (?, 'VENTA', ?, ?)";
                    try (PreparedStatement pstmtMov = conn.prepareStatement(sqlMovimiento)) {
                        pstmtMov.setInt(1, p.getId());
                        pstmtMov.setInt(2, p.getStock());
                        pstmtMov.setString(3, "Venta #" + ventaId);
                        pstmtMov.executeUpdate();
                    }
                }
                
                conn.commit();
                
                mostrarTicket(ventaId, numeroTicket, nombreCliente, 
                            metodoPago, subtotal, iva, total);
                
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Venta registrada exitosamente!\nTicket: " + numeroTicket, 
                    "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                carrito.clear();
                this.dispose();
                
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }
            
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: " + e.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.setAutoCommit(true);
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }
    
    private void mostrarTicket(int ventaId, String numeroTicket, String cliente, 
                          String metodoPago, double subtotal, double iva, double total) {
    StringBuilder ticket = new StringBuilder();
    ticket.append("══════════════════════════════════════════════\n");
    ticket.append("              TIENDA DE PINTURAS             \n");
    ticket.append("══════════════════════════════════════════════\n");
    ticket.append("Ticket: ").append(numeroTicket).append("\n");
    ticket.append("Venta ID: ").append(ventaId).append("\n");
    ticket.append("Fecha: ").append(new java.util.Date()).append("\n");
    ticket.append("Vendedor: ").append(vendedor != null ? vendedor.getNombre() : "N/A").append("\n");
    ticket.append("Cliente: ").append(cliente).append("\n");
    ticket.append("Método Pago: ").append(metodoPago).append("\n");
    ticket.append("══════════════════════════════════════════════\n");
    ticket.append("PRODUCTOS:\n");
    ticket.append("══════════════════════════════════════════════\n");
    
    for (Producto p : carrito) {
        ticket.append(String.format("%-25s x%d\n", p.getNombre(), p.getStock()));
        ticket.append(String.format("  $%.2f c/u = $%.2f\n", p.getPrecio(), p.getPrecio() * p.getStock()));
    }
    
    ticket.append("══════════════════════════════════════════════\n");
    ticket.append(String.format("SUBTOTAL:              $%.2f\n", subtotal));
    ticket.append(String.format("IVA (16%%):             $%.2f\n", iva));
    ticket.append(String.format("TOTAL:                 $%.2f\n", total));
    ticket.append("══════════════════════════════════════════════\n");
    ticket.append("         ¡GRACIAS POR SU COMPRA!             \n");
    ticket.append("══════════════════════════════════════════════\n");
    
    // Crear el área de texto
    javax.swing.JTextArea textArea = new javax.swing.JTextArea(ticket.toString());
    textArea.setEditable(false);
    textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    
    // Crear botón para guardar
    javax.swing.JButton btnGuardar = new javax.swing.JButton("💾 Guardar Ticket como TXT");
    btnGuardar.addActionListener(e -> guardarTicketArchivo(ticket.toString(), numeroTicket));
    
    // Crear panel con botón
    javax.swing.JPanel panelBotones = new javax.swing.JPanel();
    panelBotones.add(btnGuardar);
    
    // Crear panel principal
    javax.swing.JPanel panelPrincipal = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelPrincipal.add(new javax.swing.JScrollPane(textArea), java.awt.BorderLayout.CENTER);
    panelPrincipal.add(panelBotones, java.awt.BorderLayout.SOUTH);
    
    // Mostrar diálogo
    javax.swing.JOptionPane.showMessageDialog(this, panelPrincipal, 
        "Ticket de Venta - " + numeroTicket, 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);
}
    
    private void guardarTicketArchivo(String contenidoTicket, String numeroTicket) {
    // Crear selector de archivos
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    
    // Sugerir nombre de archivo
    String nombreArchivo = "Ticket_" + numeroTicket + ".txt";
    fileChooser.setSelectedFile(new java.io.File(nombreArchivo));
    
    // Mostrar diálogo de guardar
    int resultado = fileChooser.showSaveDialog(this);
    
    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fileChooser.getSelectedFile();
        
        // Asegurar extensión .txt
        if (!archivo.getName().toLowerCase().endsWith(".txt")) {
            archivo = new java.io.File(archivo.getAbsolutePath() + ".txt");
        }
        
        try (java.io.FileWriter writer = new java.io.FileWriter(archivo)) {
            writer.write(contenidoTicket);
            
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ticket guardado exitosamente en:\n" + archivo.getAbsolutePath(),
                "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al guardar el archivo:\n" + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new VentasFrameGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
